"""add subject_id to docs lps ppts

Revision ID: 037c9aee87ca
Revises: d45c3f1a4453
Create Date: 2026-06-27 20:29:18.373024

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '037c9aee87ca'
down_revision = 'd45c3f1a4453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document', 'subject', ['subject_id'], ['id'], ondelete='SET NULL')
    op.add_column('lessonplan', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'lessonplan', 'subject', ['subject_id'], ['id'], ondelete='SET NULL')
    op.add_column('pptrecord', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'pptrecord', 'subject', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pptrecord', type_='foreignkey')
    op.drop_column('pptrecord', 'subject_id')
    op.drop_constraint(None, 'lessonplan', type_='foreignkey')
    op.drop_column('lessonplan', 'subject_id')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'subject_id')
    # ### end Alembic commands ###
