"""add knowledge graph and lesson plan models

Revision ID: 072c01c24c64
Revises: fe56fa70289e
Create Date: 2026-06-27 14:09:18.757573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '072c01c24c64'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgepoint',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('grade_level', sa.Enum('PRIMARY', 'JUNIOR', 'SENIOR', name='gradelevel'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessonplan',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('grade_level', sa.Enum('PRIMARY', 'JUNIOR', 'SENIOR', name='gradelevel'), nullable=True),
    sa.Column('teaching_objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teaching_process', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledgerelation',
    sa.Column('relation_type', sa.Enum('PREREQUISITE', 'CONTAINS', 'RELATED', name='relationtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledgepoint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledgepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessonplanknowledgepointlink',
    sa.Column('lesson_plan_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_point_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledgepoint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lessonplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_plan_id', 'knowledge_point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessonplanknowledgepointlink')
    op.drop_table('knowledgerelation')
    op.drop_table('lessonplan')
    op.drop_table('knowledgepoint')
    # ### end Alembic commands ###
