"""add teacher profile fields

Revision ID: 6606c720cf20
Revises: e188b68bf2cd
Create Date: 2026-06-27 20:10:03.121427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6606c720cf20'
down_revision = 'e188b68bf2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('user', sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    op.drop_column('user', 'grade_level')
    op.drop_column('user', 'subject')
    # ### end Alembic commands ###
