"""add ppt text and style

Revision ID: ceb6418db698
Revises: 037c9aee87ca
Create Date: 2026-06-27 21:09:12.824300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ceb6418db698'
down_revision = '037c9aee87ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonplan', sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lessonplan', sa.Column('style', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessonplan', 'style')
    op.drop_column('lessonplan', 'extracted_text')
    # ### end Alembic commands ###
