"""add kp difficulty and key point

Revision ID: d45c3f1a4453
Revises: d18b41d66e2a
Create Date: 2026-06-27 20:19:10.603646

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd45c3f1a4453'
down_revision = 'd18b41d66e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgepoint', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.add_column('knowledgepoint', sa.Column('is_key_point', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgepoint', 'is_key_point')
    op.drop_column('knowledgepoint', 'difficulty')
    # ### end Alembic commands ###
