"""add user profile fields

Revision ID: e188b68bf2cd
Revises: 8f27bb835eab
Create Date: 2026-06-27 20:02:10.021448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e188b68bf2cd'
down_revision = '8f27bb835eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
